### ISSUE TITLE
Need to update to Django 1.7 to use new DB immigration. 

### ISSUE THREAD

**Issue by mave99a** [pixomobile/pixotale-issues#650]
Need to update to Django 1.7 to use new DB immigration.

**Comment by mave99a** [comment]
Hit problem during upgrade. 

http://stackoverflow.com/questions/25680803/django-1-7-upgrade-error-appregistrynotready-models-arent-loaded-yet?lq=1

/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python /Users/robmao/work/projects/pixoclub/serverside/manage.py runserver 8000
Traceback (most recent call last):
  File "/Users/robmao/work/projects/pixoclub/serverside/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/Library/Python/2.7/site-packages/django_cleanup/models.py", line 55, in <module>
    for model in find_models_with_filefield():
  File "/Library/Python/2.7/site-packages/django_cleanup/models.py", line 13, in find_models_with_filefield
    model_list = cache.get_models(app)
  File "/Library/Python/2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(_args, *_kwds)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by mave99a** [comment]
Will move to meteor in v2
